# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9c9071be82d63763781b749f519b1ec5aaf3822e5392b9330775eee5afe5eb1840c75756ace2cd75ffd8eb071a6c3b48dd430a142d4611d7996971b7b29724d

test:
  secret_key_base: d1e0750e484fbf8ebf40db83b4993ae1c691345642a2af5bea63b413a4578b02b418d5b30a50d87202a9dad3c6817eaecc28d1078ce123e6e4e249a04597cdc3
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
